name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to vps by using ssh
        run: ssh -i {{secrets.SSH_PRIVATE_KEY}} -v ubuntu@51.38.227.177 -p 60313
