name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key and gives 600
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > clave
          chmod 600 clave
      - name: Connect to vps by using ssh
        run: |
          ssh -i clave -o StrictHostKeyChecking=no ubuntu@51.38.227.177 -p 60313
      - name: Install dependecies
        run: |
          cd /var/www/portfolio
          npm i
          npm run build
          pm2 startup
          pm2 save
