name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key and gives 600
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > clave
          chmod 600 clave
      - name: Connect to vps by using ssh
        run: |
          ssh -i clave -o StrictHostKeyChecking=no ubuntu@51.38.227.177 -p 60313 << 'EOF'
            cd /var/www/portfolio
            git fetch
            git pull
            npm i
            npm run build
            pm2 delete portfolio || true
            pm2 start .output/server/index.mjs --name portfolio
            pm2 restart portfolio
            pm2 save
          EOF